config/routes.rb
Waffle::Application.routes.draw do
  get "debrief/new"
  get "debrief/create"
  root to: 'static_pages#home'

  match '/sign_up',   to: 'users#new',             via: 'get'
  match '/sign_in',   to: 'sessions#new',          via: 'get'
  match '/log_in',    to: 'sessions#new',          via: 'get'  
  match '/sign_out',  to: 'sessions#destroy',      via: 'delete'
  match '/log_out',   to: 'sessions#destroy',      via: 'delete'

  match '/help',      to: 'static_pages#help',     via: 'get'
  match '/about',     to: 'static_pages#about',    via: 'get'
  match '/contact',   to: 'static_pages#contact',  via: 'get'
  match '/userHome',  to: 'static_pages#show',     via: 'get'
  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :validations
  resources :questionnaires
  resources :block_questionnaires
  resources :blocks
  resources :answer_types
  resources :studies
  resources :questions
  resources :schedule_templates
  resources :debriefs, only: [ :new, :create, :index, :update ]
  resources :answer_sets, only: [ :create, :destroy, :index, :new, :show ]

  resources :participants, only: [ :new, :create, :show, :index ]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !current_user.nil?
      redirect_to current_user
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<head>
	<title>About Us</title>
</head>

<h1>About Us</h1>
<p>
  <div class="center">
  	The WAFFLE Project was created by a team at Franklin and Marshall College, comprised of Eliot Stone, Allison Troy, and Steele Schauer. The project began with one study - Affective Forecasting of Future Life Events. And has now has evolved into a multistudy project. 
  </div>
  <br /> The acronym WAFFLE stood for: <br /><br />
  <strong>W</strong>eb application for <br />
  <strong>A</strong>ffective <br />
  <strong>F</strong>orecasting of <br />
  <strong>F</strong>uture <br />
  <strong>L</strong>ife<br />
  <strong>E</strong>vents<br /><br />
  <div class="center">
	  More information to come in the future.
  </div>
</p>

<%= render 'shared/logos' %>

app/views/static_pages/contact.html.erb
<head>
	<title>Contact</title>
</head>
<h1>Contact Us</h1>
<p>
	Contact the WAFFLE Team at Franklin and Marshall College by emailing emotionlab@fandm.edu or go to the 	<a href="http://fandm.edu">Franklin and Marshal College</a> webpage.
</p>

<%= render 'shared/logos' %>

app/views/static_pages/help.html.erb
<head>
	<title>Help</title>
</head>
<h1>Help</h1>
  <h2>Frequently Asked Questions</h2>
    <p> 
      Where is the log out button? <br />
      The log out button is located in the drop-down menu that is accessed by clicking on your email. It is located in the top right corner of every page (including this one), in the header. <br /> <br />
      How long am I logged into my account? <br />
      You are logged into your account unless you log out manually. This was designed for the ease of the user (likely you) but can be less secure. Please log out after each session unless you are sure your computer is secure and never give out your password to anyone. <br /> <br />
      I forgot my password, is there a way I can access my account? <br />
      Yes, this is a common occurence. Simply go to the log in page and click the Reset password link. This link will send an email to your account email with a form to fill out for a new password. <br /> <br />
      I deleted or my email provider deleted my validation email, what can I do? <br />
      Go to the log in page and click the link for resending a validation email, then check your email and spam folders.
    </p>
    <br />
  <h2>Other Questions?</h2>
    <p>
    	For help, contact the WAFFLE Team at Franklin and Marshall College by emailing sschauer@fandm.edu
    </p>

<%= render 'shared/logos' %>

app/views/static_pages/home.html.erb
<head>
	<title>Waffle Home</title>
</head>

<div class="center hero-unit">
	<h1>Welcome to the WAFFLE Project</h1>

	<h2>
		Created by the EmoLab at Franklin and Marshall College.
	</h2>

	<%= link_to "Sign up now!", sign_up_path, class: "btn btn-large btn-primary" %>
    <%= link_to "Log in", log_in_path, class: "btn btn-large btn-primary" %>
</div>

<%= render 'shared/logos' %>