config/routes.rb
Waffle::Application.routes.draw do
  get "debrief/new"
  get "debrief/create"
  root to: 'static_pages#home'

  match '/sign_up',   to: 'users#new',             via: 'get'
  match '/sign_in',   to: 'sessions#new',          via: 'get'
  match '/log_in',    to: 'sessions#new',          via: 'get'  
  match '/sign_out',  to: 'sessions#destroy',      via: 'delete'
  match '/log_out',   to: 'sessions#destroy',      via: 'delete'

  match '/help',      to: 'static_pages#help',     via: 'get'
  match '/about',     to: 'static_pages#about',    via: 'get'
  match '/contact',   to: 'static_pages#contact',  via: 'get'
  match '/userHome',  to: 'static_pages#show',     via: 'get'
  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :validations
  resources :questionnaires
  resources :block_questionnaires
  resources :blocks
  resources :answer_types
  resources :studies
  resources :questions
  resources :schedule_templates
  resources :debriefs, only: [ :new, :create, :index, :update ]
  resources :answer_sets, only: [ :create, :destroy, :index, :new, :show ]

  resources :participants, only: [ :new, :create, :show, :index ]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participants

  has_many :studies, through: :participants
  attr_accessor :password
  before_save :encrypt_password
  before_save { self.email = email.downcase }
  before_create :create_auth_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
  validates :email, 
    presence: true,
    length: { minimum: 5 }, 
    format: { with: VALID_EMAIL_REGEX }, 
    uniqueness: { case_sensitive: false }
  validates :password,
    length: { on: :create, minimum: 5 },
    presence: { on: :create },
    confirmation: true
  validates :password_confirmation, presence: { on: :create }

  self.per_page = 10

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if self.password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def User.new_auth_token
    SecureRandom.urlsafe_base64
  end

  def User.new_valid_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def send_password_reset
    create_auth_token
    self.password_reset_sent_at = Time.zone.now
    save!(validate: false)
    UserMailer.password_reset(self).deliver
  end

  def send_validation
    create_valid_token
    save!(validate: false)
    UserMailer.validation(self).deliver
  end

  def pending_schedule_entries(study=nil)
    pending = []
    self.participants.each do |participant|
      current_pending = participant.next_schedule_entry
      if !current_pending.nil? and 
          (study.nil? or current_pending.study == study)
        pending.append(current_pending)
      end
    end
    pending
  end

  private
    def create_auth_token
      self.auth_token = User.digest(User.new_auth_token)
    end

    def create_valid_token
      self.valid_token = User.digest(User.new_valid_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_be_logged_in, except: [ :new, :create ]
  before_action :must_be_logged_out, only: [ :new, :create ]
  before_action :must_be_correct_user, only: [ :edit, :update, :destroy, :show ]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @studies = Study.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Signed up! Thank you! 
        You should receive a validation email shortly."
      @user.send_validation
      redirect_to users_url
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user, notice: "Profile updated!"
    else
      render 'edit'
    end
  end

  def destroy
    destroying_self = current_user.id.to_s == params[:id]
    was_admin_user = is_admin_user?
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    if was_admin_user && !destroying_self
      redirect_to users_url
    else
      redirect_to root_url
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password,
         :password_confirmation, :name, :address_line_one, 
         :address_line_two, :city, :state, :zip_code, 
         :auth_token, :password_reset_token )
    end

    def must_be_logged_out
      if logged_in? && !is_admin_user?
        redirect_to root_url, notice: "You already have an account."
      end
    end

    def must_be_correct_user
      if !is_admin_user?
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_pending_questionnaires.html.erb
<div>
  <% if @user.pending_schedule_entries.length > 0 %>
      You have the following questionnaires to take:
        <%= render partial: "shared/take_questionnaire_banner",
            locals: { schedule_entries: 
                      @user.pending_schedule_entries
                    } %>
  <% else %>
      You have no questionnaires to take.
  <% end %>
</div>

app/views/users/_study_participation.html.erb
<div class="panel-body text-left study-panel">
    <div class="panel-body study-banner-panel">
        <%= link_to participant.study.title, participant.study %></li>
    </div>
    <div class="study-participation-details-container panel-body">
        <div class="study-details-panel study-participation-sign-up-date panel-body">
            Signed Up: <%= participant.created_at %>
        </div>
        <div class="study-details-panel study-participation-questionnaire-time-frame-panel panel-body">
            Study Length: <%= participant.study_length_in_days %> days
        </div>
        <div class="study-details-panel study-participation-questionnaire-count-panel panel-body">
            Questionnaires Taken: <%= participant.questionnaires_taken %> /
            <%= participant.total_questionnaires %>
        </div>
        <% if participant.total_questionnaires == participant.questionnaires_taken %>
          <div>
            You have completed the study. View <%= link_to "Debrief", new_debrief_path %> form.
          </div>
        <% end %>
    </div>
</div>

app/views/users/_user.html.erb
<% if current_user.is_admin? %>
  <%= user.name %> |
  <%= link_to user.email, user %> |
  <%= user.state %> |
  <%= link_to 'Edit', edit_user_path(user) %> |
  <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?'} %><br/>
  <li class="divider"></li>
<% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<p><strong>For security reasons, please input your password and password confirmation. You may change your password here or keep it the same.</strong></p>

    <%= form_for(@user, html: { class: "form-horizontal" }) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label :email, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :email, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :password, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.password_field :password, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation, "Confirm Password", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
        </div>

        <hr>

        <div class="form-group">
            <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :address_line_one, "Address Line One", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :address_line_one, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :address_line_two, "Address Line Two", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :address_line_two, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :city, "City", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :city, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :state, "State", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.select(:state, options_for_select([['AL'], ['AK'],
                  ['AZ'], ['AR'], ['CA'], ['CO'], ['CT'], ['DE'], ['FL'],
                  ['GA'], ['HI'], ['ID'], ['IL'], ['IN'], ['IA'], ['KS'],
                  ['KY'], ['LA'], ['ME'], ['MD'], ['MA'], ['MI'], ['MN'],
                  ['MS'], ['MO'], ['MT'], ['NE'], ['NV'], ['NH'], ['NJ'],
                  ['NM'], ['NY'], ['NC'], ['ND'], ['OH'], ['OK'], ['OR'],
                  ['PA'], ['RI'], ['SC'], ['SD'], ['TN'], ['TX'], ['UT'],
                  ['VT'], ['VA'], ['WA'], ['WV'], ['WI'], ['WY']]), {}, { class: "form-control" }) %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :zip_code, "Zip Code", class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
                <%= f.text_field :zip_code, class: "form-control" %>
            </div>
        </div>

        <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/users/index.html.erb
<!--only for the admin-->
<head>
	<title>All users</title>
</head>
<h1>All users</h1>

<div>
  <% if current_user.is_admin? %>
    Format: Name | Participant<br/>
    Email | State | Actions <br/><br/>
  <% end %>
</div>

<%= will_paginate %>
<ul class="users">
 <%= render @users %> <! located at _user.html.erb > 
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<head>
	<title>Sign Up</title>
</head>

<h1>Sign Up</h1>

<div class="row">
	<div class="span5 offset3">
		<%= form_for @user do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

<%= render 'shared/logos' %>

app/views/users/show.html.erb
<div class="panel-header waffle-header">
    <h1>User Home Page</h1>
</div>

<div class="panel-body">
    <% if @user.participants.length > 0 %>
        <%= render partial: 'pending_questionnaires', locals: { user: @user } %>

        You are participating in the following studies:
        <% current_user.participants.each do |participant| %>
            <%= render partial: 'study_participation',
                    locals: { participant: participant } %>
        <% end %>
    <% else %>
        You are not participating in any studies. <br />
        Choose a study to join:
        <%= render partial: 'shared/all_studies' %>
    <% end %>
</div>

app/views/users/validate.html.erb
<head>
	<title>Edit user</title>
</head>

<h1>Edit User Information</h1>

<p>For security reasons, you must input your password and password confirmation. You may change your password here or keep it the same.</p>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

<%= render 'shared/logos' %>