config/routes.rb
Waffle::Application.routes.draw do
  get "debrief/new"
  get "debrief/create"
  root to: 'static_pages#home'

  match '/sign_up',   to: 'users#new',             via: 'get'
  match '/sign_in',   to: 'sessions#new',          via: 'get'
  match '/log_in',    to: 'sessions#new',          via: 'get'  
  match '/sign_out',  to: 'sessions#destroy',      via: 'delete'
  match '/log_out',   to: 'sessions#destroy',      via: 'delete'

  match '/help',      to: 'static_pages#help',     via: 'get'
  match '/about',     to: 'static_pages#about',    via: 'get'
  match '/contact',   to: 'static_pages#contact',  via: 'get'
  match '/userHome',  to: 'static_pages#show',     via: 'get'
  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :validations
  resources :questionnaires
  resources :block_questionnaires
  resources :blocks
  resources :answer_types
  resources :studies
  resources :questions
  resources :schedule_templates
  resources :debriefs, only: [ :new, :create, :index, :update ]
  resources :answer_sets, only: [ :create, :destroy, :index, :new, :show ]

  resources :participants, only: [ :new, :create, :show, :index ]

end

app/models/study.rb
class Study < ActiveRecord::Base
  has_many :questionnaires, dependent: :destroy
  has_many :schedule_templates, dependent: :destroy
  has_many :participants, dependent: :destroy

  validates :title,
    presence: true,
    uniqueness: true
  validates :label,
    uniqueness: true,
    label: true

  self.per_page = 10
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :must_be_logged_in
  before_action :must_be_admin, only: [ :edit, :update, :destroy, :new, :create ]

  def create
    @study = Study.new(study_params)
    if @study.save
      render :json => @study.to_json
    else
      render :json => { :errors => @study.errors.full_messages }
    end
  end

  def show
    @study = Study.find(params[:id])
    @current_participant = current_user.participants.where(study_id: params[:id]).take
  end

  def update
    @study = Study.find(params[:id])
    if @study.update_attributes(study_params)
      render :json => @study.to_json
    else
      render :json => { :errors => @study.errors.full_messages }
    end
  end

  def index
    @studies = Study.all
  end

  def destroy
    Study.find(params[:id]).destroy
    flash[:success] = "Study deleted."
    redirect_to studies_path
  end

  private
  
  def study_params
    params.require(:study).permit(:title, :label)
  end
end

app/controllers/studys_controller.rb
class StudysController < ApplicationController
  def new
    @study = Study.new
    questionnaire = @study.questionnaires.build
    questionnaire.blocks.build  
  end

  def create
    @study = Study.new(study_params)
    if @study.save
      flash[:notice] = "Study created succesfully."
      redirect_to @study
    else
      render :action => 'new'
    end
  end

  def show
    @study = Study.find(params[:id])
  end

  def edit
    @study = Study.find(params[:id])
  end

  def update
    @study = Study.find(params[:id])
    if @study.update_attributes(study_params)
      redirect_to @study, notice: "Study updated!"
    else
      render 'edit'
    end
  end

  def index
    @studys = Study.paginate(page: params[:page])
  end

  def destroy
    if current_user.admin?
      Study.find(params[:id]).destroy
      flash[:success] = "Study deleted."
      redirect_to studys_path
    else
      flash[:notice] = "Only admins may delete a study."
    end
  end

  private
  
  def study_params
    params.require(:study).permit(:title, questionnaires_attributes:
      [:label, :id, :_destroy, blocks_attributes: 
      [:label, :id, :_destroy, questions_attributes: 
      [:label, :text, :id, :_destroy, answers_attributes: 
      [:value, :id, :participant_id, :_destroy], choices_attributes: 
      [:value, :id, :_destroy]]]])
  end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studys/_form.html.erb
<%= form_for @study do |f| %>
  <% if current_user.admin %>
    <p>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <%= f.fields_for :questionnaires do |builder| %>
      <%= render 'questionnaire_fields', :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Questionnaire", f, :questionnaires %></p>
    <p><%= f.submit "Submit Study", class: "btn btn-primary btn-large btn-block" %></p>
    <%= link_to "List of Current Studies", studys_path %> 
  <% else %>
    <p>
      <strong><%= @study.title %></strong>
      <ol>
        <% for questionnaire in @study.questionnaires %>
          <li><%=h questionnaire.label %></li>
        <% end %> 
      </ol>
    </p>
  <% end %>
<% end %>

app/views/studys/_study.html.erb
<% if current_user %>
  <strong><%= study.title %></strong><br />
  <ol>
    <% for questionnaire in study.questionnaires %>
      <li><i><%=h questionnaire.label %></i></li>
      <ol>
        <% for block in questionnaire.blocks %>
          <li><b><%=h blocks.label %></b></li>
            <ol>
              <% for question in block.questions %>
                <li><b><%=h question.label %></b></li>
                <%=h question.text %>
                <ol>
                  <% for answer in question.answers %>
                    <li><i><%=h answer.value %></i></li>
                  <% end %>
                </ol>
              <% end %>
            </ol>
        <% end %> <br />
      </ol>
    <% end %>
  </ol>
  <%= link_to 'Edit Study', edit_study_path(study) %>
<% end %>
<% if current_user.admin? %>
  | <%= link_to 'Delete', study, method: :delete, data: { confirm: 'Are you sure?'} %><br/>
<% else %>
<br/>
<% end %><br />

app/views/studys/index.html.erb
<!--only for the admin-->
<head>
	<title>All Studies</title>
</head>
<h1>All Studies</h1>
<%= render 'shared/logos' %><br />

<div>
  <% if current_user %>
    <strong>Format:</strong> Study Title with actions listed below<br/><br/>
</div>
    <%= will_paginate %>
    <ul class="studys">
      <%= render @studys %> <! located at _study.html.erb > 
    </ul>
    <%= will_paginate %>
    <% if current_user.admin? %>
      <%= link_to "Create a Study", new_study_path %>
    <% end %>
  <% end %>

app/views/studys/show.html.erb
<head>
  <title>Study</title>
</head>

<h1>Study Page</h1>

<%= render 'shared/logos' %>
<br />
<strong><br />Format:</strong> Study Title with content and actions listed below<br/><br/> 
<div class="studys">
  <strong>
    <%= @study.title %>
  </strong><br />
  <ol>
  	<% for questionnaire in study.questionnaires %>
      <li><i><%=h questionnaire.label %></i></li>
      <ol>
        <% for block in questionnaire.blocks %>
          <li><b><%=h blocks.label %></b></li>
            <ol>
              <% for question in block.questions %>
                <li><b><%=h question.label %></b></li>
                <%=h question.text %>
                <ol>
                  <% for answer in question.answers %>
                    <li><i><%=h answer.value %></i></li>
                  <% end %>
                </ol>
              <% end %>
            </ol>
        <% end %> <br />
      </ol>
    <% end %>
  </ol>
  	<%= link_to 'Edit', edit_study_path(@study) %> |
  	<%= link_to 'Delete', @study, method: :delete, data: { confirm: 'Are you sure?'} %>
    <br/> 
</div>

<p>
  <%= link_to "View all Studies", studys_path %>
</p>