config/routes.rb
Waffle::Application.routes.draw do
  get "debrief/new"
  get "debrief/create"
  root to: 'static_pages#home'

  match '/sign_up',   to: 'users#new',             via: 'get'
  match '/sign_in',   to: 'sessions#new',          via: 'get'
  match '/log_in',    to: 'sessions#new',          via: 'get'  
  match '/sign_out',  to: 'sessions#destroy',      via: 'delete'
  match '/log_out',   to: 'sessions#destroy',      via: 'delete'

  match '/help',      to: 'static_pages#help',     via: 'get'
  match '/about',     to: 'static_pages#about',    via: 'get'
  match '/contact',   to: 'static_pages#contact',  via: 'get'
  match '/userHome',  to: 'static_pages#show',     via: 'get'
  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets
  resources :validations
  resources :questionnaires
  resources :block_questionnaires
  resources :blocks
  resources :answer_types
  resources :studies
  resources :questions
  resources :schedule_templates
  resources :debriefs, only: [ :new, :create, :index, :update ]
  resources :answer_sets, only: [ :create, :destroy, :index, :new, :show ]

  resources :participants, only: [ :new, :create, :show, :index ]

end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_validation if user
    redirect_to root_url, :notice => "Email validation sent!"
  end

  def edit
    @user = User.find_by_valid_token!(params[:id])
    if @user
      @user.is_valid = true
      @user.save!(validate: false)
      redirect_to root_url, :notice => "Email validated!"
    else
      redirect_to root_url, :notice => "Invalid user or link."
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password,
         :password_confirmation, :name, :address_line_one, 
         :address_line_two, :city, :state, :zip_code, 
         :auth_token, :password_reset_token, :valid_token, :is_valid )
    end

end

app/helpers/validations_helper.rb
module ValidationsHelper
end

app/views/validations/edit.html.erb
<head>
  <title>Email Validation Page</title>
</head>

<h1>Validate Email </h1>

<div class="row">
  <div class="span5 offset3">
    <%= form_for @user, :url => validation_path(params[:id]) do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.label :Please_check_the_box_below_to_validate_and_then_click_submit %>
      Validate? <%= f.check_box :is_valid %><br/><br/>

      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= render 'shared/logos' %>

app/views/validations/new.html.erb
<head>
  <title>Email Validation Page</title>
</head>

<h1>Validate Email </h1>

<div class="row">
  <div class="span5 offset3">
    <%= form_tag validations_path, :method => :post do %>
      <div class="field">
        <%= label_tag :email %>
        <%= text_field_tag :email, params[:email] %>
      </div>
      <%= submit_tag "Validate", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= render 'shared/logos' %>